#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Async-Interrupt
Version  : 1.24
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Async-Interrupt-1.24.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Async-Interrupt-1.24.tar.gz
Source1  : http://http.debian.net/debian/pool/main/liba/libasync-interrupt-perl/libasync-interrupt-perl_1.24-1.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 BSD-2-Clause GPL-1.0 GPL-2.0
Requires: perl-Async-Interrupt-lib
Requires: perl-Async-Interrupt-license
Requires: perl-Async-Interrupt-man
Requires: perl(Canary::Stability)
Requires: perl(common::sense)
BuildRequires : perl(Canary::Stability)
BuildRequires : perl(common::sense)

%description
NAME
Async::Interrupt - allow C/XS libraries to interrupt perl asynchronously
SYNOPSIS
use Async::Interrupt;

%package lib
Summary: lib components for the perl-Async-Interrupt package.
Group: Libraries
Requires: perl-Async-Interrupt-license

%description lib
lib components for the perl-Async-Interrupt package.


%package license
Summary: license components for the perl-Async-Interrupt package.
Group: Default

%description license
license components for the perl-Async-Interrupt package.


%package man
Summary: man components for the perl-Async-Interrupt package.
Group: Default

%description man
man components for the perl-Async-Interrupt package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Async-Interrupt-1.24
mkdir -p %{_topdir}/BUILD/Async-Interrupt-1.24/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Async-Interrupt-1.24/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Async-Interrupt
cp COPYING %{buildroot}/usr/share/doc/perl-Async-Interrupt/COPYING
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Async-Interrupt/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Async/Interrupt.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Async/Interrupt/Interrupt.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Async-Interrupt/COPYING
/usr/share/doc/perl-Async-Interrupt/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Async::Interrupt.3
